server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.228.102:3306/HuaJuWelcome?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    druid:
      #监控SpringBean
      aop-patterns: com.qzx.recruit.*
      # 底层开启功能，stat（sql监控），wall（防火墙）
      filters: stat,wall
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: mysql
        reset-enable: false
      # 监控web需要开启
      web-stat-filter:
        enabled: true
      # filter的配置
      filter:
        # 对上面filters里面的stat的详细配置（sql监控配置）
        stat:
          slow-sql-millis: 3000
          log-slow-sql: true
          enabled: true
        # 防火墙配置 对某些sql语句进行拦截
        wall:
          config:
            drop-table-allow: false
          enabled: true




  #    #springboot2.0+默认数据源类型为hikari
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      connection-test-query: SELECT 1 FROM DUAL
#      #从池返回的连接的默认自动提交行为
#      auto-commit: true
#      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
#      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
#      idle-timeout: 30000
#      #连接池名称，默认HikariPool-1
#      pool-name: SpringBootDemoHikariCP
#
#      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
#      max-lifetime: 60000
#      connection-timeout: 30000


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapperXML/*.xml
  configuration:
    #带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
